# Generated by Django 2.2.24 on 2022-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0029_auto_20210202_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefill_PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifier')),
                ('description', models.TextField(verbose_name='Description')),
                ('users', models.ManyToManyField(blank=True, related_name='_prefill_pdf_users_+', related_query_name='+', to='base.ApiUser')),
            ],
            options={
                'verbose_name': 'Pré-remplissage de fichier PDF',
            },
        ),
    ]
